# Generated by Django 2.2.1 on 2020-01-01 22:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='completeuser',
            name='photo',
        ),
    ]
